name: Meister TAS/TAF

on: push

jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: Regression on Chrome
    #container:
    #  image: cypress/browsers:latest
    #  options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
        with:
          browser: chrome
          build: npm run build
          start: npm start