name: Meister TAS Groovy

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all the branches
  push:
    branches: [ "**" ]

jobs:
  groovy:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2.7 and pypy3.9
      matrix:
        java-version: ["17"]

    steps:
      - uses: actions/checkout@master # THIS IS IMPORTANT
      # - uses: actions/checkout@v3
      - uses: actions/setup-java@v3   # THIS IS IMPORTANT
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Install Dependencies
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk version
          ls /usr/lib/jvm
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          echo $JAVA_HOME
          sdk install groovy
        continue-on-error: true
      - name: Show library versions
        run: |
          sdk version
          java --version
          javac --version
          groovy --version
          groovyc --version
          chrome --version
      - name: Groovy Tests
        run: |
          java 
      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: robot-framework-benchmark/robot-test-results